# Site settings
name: Isaias Xicale
title: Isaias Xicale | Sr Fullstack Developer
description: Software engineer focused on building products for the web with passion for design and technology.
url: https://ixicale.github.io/
baseurl: ''
email: ixicaleescalante@gmail.com
logo: https://ixicale.github.io/assets/svg/light_logo_icon.svg
social:
  - title: email
    url: mailto:ixicaleescalante@gmail.com
keywords: fullstack, web, python, xicale, isaias, ixicale, software, engineer, developer, javascript, golang, aws, latam

sass:
  sass_dir: _sass
  style: compressed

include:
  - assets/css

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'package.json'
  - 'package-lock.json'
  - 'LICENSE'
  - 'local.sh'
  - 'Dockerfile'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
